// SPDX-License-Identifier: Apache-2.0
// Ported from oMLX (jundot/omlx) omlx/custom_kernels/qwen35_prefill/gdn.py @ 730bd6a
// (gated_delta_pipelined, jundot/omlx#4006): generated by `_pipelined_source(12)`, then made
// generic over the state (StT) and output (OutT) dtypes, the contract of the blocked kernel.
    constexpr int TB = 12;
    constexpr int DB = 16;
    constexpr int NT = 128;
    const int tid = thread_position_in_threadgroup.x;
    const int hv = threadgroup_position_in_grid.y;
    const int b = threadgroup_position_in_grid.z;
    const int hk = hv / (Hv / Hk);
    const int dv0 = threadgroup_position_in_grid.x * DB;
    const int rg = tid / 8;
    const int seg = tid % 8;

    threadgroup InT k_s[TB][Dk];
    threadgroup InT q_s[TB][Dk];
    threadgroup float v_s[TB][DB];
    threadgroup float g_s[TB];
    threadgroup float b_s[TB];
    threadgroup OutT y_s[TB][DB];

    const size_t krow = (size_t)Hk * Dk;
    const size_t vrow = (size_t)Hv * Dv;
    const device InT* k_base = k + ((size_t)b * T * Hk + hk) * Dk;
    const device InT* q_base = q + ((size_t)b * T * Hk + hk) * Dk;
    const device InT* v_base = v + ((size_t)b * T * Hv + hv) * Dv + dv0;
    device OutT* y_base = y + ((size_t)b * T * Hv + hv) * Dv + dv0;

    float4 st[4];
    {
        const device vec<StT, 4>* S_in = (const device vec<StT, 4>*)(
            state_in + (((size_t)b * Hv + hv) * Dv + dv0 + rg) * Dk);
        for (int i = 0; i < 4; ++i) st[i] = float4(S_in[seg + 8 * i]);
    }

    constexpr int KQ4 = TB * Dk / 4;
    constexpr int NKQ = (KQ4 + NT - 1) / NT;
    constexpr int V4 = TB * DB / 4;
    constexpr int NV = (V4 + NT - 1) / NT;
    vec<InT, 4> pk[NKQ];
    vec<InT, 4> pq[NKQ];
    vec<InT, 4> pv[NV];
    float pg = 0.0f, pb = 0.0f;
#define GDN_PIPE_FETCH(T0N) { \
        const int ttn = min(TB, T - (T0N)); \
        for (int j = 0; j < NKQ; ++j) { \
            const int p = tid + j * NT; \
            if (p < ttn * (Dk / 4)) { \
                const int r = p / (Dk / 4), c4 = p % (Dk / 4); \
                const size_t off = (size_t)((T0N) + r) * krow + 4 * c4; \
                pk[j] = *(const device vec<InT, 4>*)(k_base + off); \
                pq[j] = *(const device vec<InT, 4>*)(q_base + off); \
            } \
        } \
        for (int j = 0; j < NV; ++j) { \
            const int p = tid + j * NT; \
            if (p < ttn * (DB / 4)) { \
                const int r = p / (DB / 4), c4 = p % (DB / 4); \
                pv[j] = *(const device vec<InT, 4>*)( \
                    v_base + (size_t)((T0N) + r) * vrow + 4 * c4); \
            } \
        } \
        if (tid < ttn) { \
            pg = (float)g[((size_t)b * T + (T0N) + tid) * Hv + hv]; \
            pb = (float)beta[((size_t)b * T + (T0N) + tid) * Hv + hv]; \
        } \
    }
    GDN_PIPE_FETCH(0)

    float4 k_next[4];
    float g_next = 0.0f, b_next = 0.0f, v_next = 0.0f;
    float pq_prev = 0.0f;
    float pq4[4] = {0.0f, 0.0f, 0.0f, 0.0f};
    for (int t0 = 0; t0 < T; t0 += TB) {
        const int tt = min(TB, T - t0);
        for (int j = 0; j < NKQ; ++j) {
            const int p = tid + j * NT;
            if (p < tt * (Dk / 4)) {
                const int r = p / (Dk / 4), c4 = p % (Dk / 4);
                *(threadgroup vec<InT, 4>*)(&k_s[r][4 * c4]) = pk[j];
                *(threadgroup vec<InT, 4>*)(&q_s[r][4 * c4]) = pq[j];
            }
        }
        for (int j = 0; j < NV; ++j) {
            const int p = tid + j * NT;
            if (p < tt * (DB / 4)) {
                const int r = p / (DB / 4), c4 = p % (DB / 4);
                *(threadgroup float4*)(&v_s[r][4 * c4]) = float4(pv[j]);
            }
        }
        if (tid < tt) {
            g_s[tid] = pg;
            b_s[tid] = pb;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        if (t0 + TB < T) GDN_PIPE_FETCH(t0 + TB)
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[0][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[0][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[0][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[0][4 * (seg + 8 * 3)]));
g_next = g_s[0]; b_next = b_s[0]; v_next = v_s[0][rg];

        if (tt == TB) {
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(0) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(0) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(0) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(0) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(0) + 1]; b_next = b_s[(0) + 1]; v_next = v_s[(0) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[0][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[0][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[0][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[0][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[0] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(1) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(1) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(1) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(1) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(1) + 1]; b_next = b_s[(1) + 1]; v_next = v_s[(1) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[1][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[1][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[1][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[1][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[1] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(2) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(2) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(2) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(2) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(2) + 1]; b_next = b_s[(2) + 1]; v_next = v_s[(2) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[2][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[2][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[2][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[2][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[2] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(3) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(3) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(3) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(3) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(3) + 1]; b_next = b_s[(3) + 1]; v_next = v_s[(3) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[3][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[3][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[3][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[3][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[3] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(4) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(4) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(4) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(4) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(4) + 1]; b_next = b_s[(4) + 1]; v_next = v_s[(4) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
{
const bool qb2 = (seg & 4) != 0, qb1 = (seg & 2) != 0;
float qa = qb2 ? pq4[2] : pq4[0];
float qb = qb2 ? pq4[3] : pq4[1];
qa += simd_shuffle_xor(qb2 ? pq4[0] : pq4[2], 4);
qb += simd_shuffle_xor(qb2 ? pq4[1] : pq4[3], 4);
float qx = qb1 ? qb : qa;
qx += simd_shuffle_xor(qb1 ? qa : qb, 2);
qx += simd_shuffle_xor(qx, 1);
if ((seg & 1) == 0) y_s[0 + (qb2 ? 2 : 0) + (qb1 ? 1 : 0)][rg] = static_cast<OutT>(qx);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[4][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[4][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[4][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[4][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[0] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(5) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(5) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(5) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(5) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(5) + 1]; b_next = b_s[(5) + 1]; v_next = v_s[(5) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[5][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[5][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[5][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[5][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[1] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(6) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(6) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(6) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(6) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(6) + 1]; b_next = b_s[(6) + 1]; v_next = v_s[(6) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[6][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[6][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[6][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[6][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[2] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(7) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(7) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(7) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(7) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(7) + 1]; b_next = b_s[(7) + 1]; v_next = v_s[(7) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[7][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[7][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[7][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[7][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[3] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(8) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(8) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(8) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(8) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(8) + 1]; b_next = b_s[(8) + 1]; v_next = v_s[(8) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
{
const bool qb2 = (seg & 4) != 0, qb1 = (seg & 2) != 0;
float qa = qb2 ? pq4[2] : pq4[0];
float qb = qb2 ? pq4[3] : pq4[1];
qa += simd_shuffle_xor(qb2 ? pq4[0] : pq4[2], 4);
qb += simd_shuffle_xor(qb2 ? pq4[1] : pq4[3], 4);
float qx = qb1 ? qb : qa;
qx += simd_shuffle_xor(qb1 ? qa : qb, 2);
qx += simd_shuffle_xor(qx, 1);
if ((seg & 1) == 0) y_s[4 + (qb2 ? 2 : 0) + (qb1 ? 1 : 0)][rg] = static_cast<OutT>(qx);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[8][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[8][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[8][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[8][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[0] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(9) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(9) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(9) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(9) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(9) + 1]; b_next = b_s[(9) + 1]; v_next = v_s[(9) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[9][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[9][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[9][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[9][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[1] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(10) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(10) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(10) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(10) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(10) + 1]; b_next = b_s[(10) + 1]; v_next = v_s[(10) + 1][rg];
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[10][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[10][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[10][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[10][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[2] = o2.x + o2.y;
}
{
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[11][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[11][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[11][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[11][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq4[3] = o2.x + o2.y;
}
{
const bool qb2 = (seg & 4) != 0, qb1 = (seg & 2) != 0;
float qa = qb2 ? pq4[2] : pq4[0];
float qb = qb2 ? pq4[3] : pq4[1];
qa += simd_shuffle_xor(qb2 ? pq4[0] : pq4[2], 4);
qb += simd_shuffle_xor(qb2 ? pq4[1] : pq4[3], 4);
float qx = qb1 ? qb : qa;
qx += simd_shuffle_xor(qb1 ? qa : qb, 2);
qx += simd_shuffle_xor(qx, 1);
if ((seg & 1) == 0) y_s[8 + (qb2 ? 2 : 0) + (qb1 ? 1 : 0)][rg] = static_cast<OutT>(qx);
}

        } else {
for (int t = 0; t < tt; ++t) {
float4 kc[4];
for (int i = 0; i < 4; ++i) kc[i] = k_next[i];
const float gc = g_next, bc = b_next, vc = v_next;
if (t + 1 < tt) {
k_next[0] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(t) + 1][4 * (seg + 8 * 0)]));
k_next[1] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(t) + 1][4 * (seg + 8 * 1)]));
k_next[2] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(t) + 1][4 * (seg + 8 * 2)]));
k_next[3] = float4(*(const threadgroup vec<InT, 4>*)(&k_s[(t) + 1][4 * (seg + 8 * 3)]));
g_next = g_s[(t) + 1]; b_next = b_s[(t) + 1]; v_next = v_s[(t) + 1][rg];
}
float2 a2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = st[i] * gc;
    a2 = fma(st[i].xy, kc[i].xy, a2);
    a2 = fma(st[i].zw, kc[i].zw, a2);
}
if ((t) > 0) {
float yq = pq_prev;
yq += simd_shuffle_down(yq, 4);
yq += simd_shuffle_down(yq, 2);
yq += simd_shuffle_down(yq, 1);
if (seg == 0) y_s[(t) - 1][rg] = static_cast<OutT>(yq);
}
float p = a2.x + a2.y;
p += simd_shuffle_xor(p, 4);
p += simd_shuffle_xor(p, 2);
p += simd_shuffle_xor(p, 1);
float4 qc[4];
qc[0] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[t][4 * (seg + 8 * 0)]));
qc[1] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[t][4 * (seg + 8 * 1)]));
qc[2] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[t][4 * (seg + 8 * 2)]));
qc[3] = float4(*(const threadgroup vec<InT, 4>*)(&q_s[t][4 * (seg + 8 * 3)]));
const float delta = (vc - p) * bc;
float2 o2 = 0.0f;
for (int i = 0; i < 4; ++i) {
    st[i] = fma(kc[i], float4(delta), st[i]);
    o2 = fma(st[i].xy, qc[i].xy, o2);
    o2 = fma(st[i].zw, qc[i].zw, o2);
}
pq_prev = o2.x + o2.y;
}
{
float yq = pq_prev;
yq += simd_shuffle_down(yq, 4);
yq += simd_shuffle_down(yq, 2);
yq += simd_shuffle_down(yq, 1);
if (seg == 0) y_s[tt - 1][rg] = static_cast<OutT>(yq);
}

        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (int p = tid; p < tt * (DB / 4); p += NT) {
            const int r = p / (DB / 4), c4 = p % (DB / 4);
            *(device vec<OutT, 4>*)(y_base + (size_t)(t0 + r) * vrow + 4 * c4) =
                *(threadgroup vec<OutT, 4>*)(&y_s[r][4 * c4]);
        }
    }
#undef GDN_PIPE_FETCH

    {
        device vec<StT, 4>* S_out = (device vec<StT, 4>*)(
            state_out + (((size_t)b * Hv + hv) * Dv + dv0 + rg) * Dk);
        for (int i = 0; i < 4; ++i) S_out[seg + 8 * i] = vec<StT, 4>(st[i]);
    }
