#!/usr/bin/env python3
"""Generate tokenizer general-category tables with Python 3.14 / Unicode 16.0.
Only classifies codepoints; each tokenizer's declared regex selects how classes
are combined. No language-specific segmentation rules live in these tables.
"""
import unicodedata as u
from pathlib import Path
assert u.unidata_version == '16.0.0', u.unidata_version
rows=[]
for cp in range(0x110000):
    cat={'L':'letter','M':'mark','N':'number'}.get(u.category(chr(cp))[0])
    if cat is None:continue
    if rows and rows[-1][1]+1==cp and rows[-1][2]==cat:rows[-1][1]=cp
    else:rows.append([cp,cp,cat])
text='''// Generated by scripts/gen-tokenizer-unicode.py using Unicode 16.0.0.
// Unicode general categories, not language-specific tokenization policy.
pub const Category = enum { other, letter, mark, number };
const Range = struct { first: u21, last: u21, category: Category };
pub fn category(cp: u21) Category {
    if (cp < 128) {
        if ((cp >= 'a' and cp <= 'z') or (cp >= 'A' and cp <= 'Z')) return .letter;
        if (cp >= '0' and cp <= '9') return .number;
        return .other;
    }
    var lo: usize = 0;
    var hi: usize = ranges.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const r = ranges[mid];
        if (cp < r.first) hi = mid else if (cp > r.last) lo = mid + 1 else return r.category;
    }
    return .other;
}
// Unicode White_Space property (not Python's broader isspace()).
pub fn whitespace(cp: u21) bool {
    return (cp >= 0x09 and cp <= 0x0d) or cp == 0x20 or cp == 0x85 or
        cp == 0xa0 or cp == 0x1680 or (cp >= 0x2000 and cp <= 0x200a) or
        cp == 0x2028 or cp == 0x2029 or cp == 0x202f or cp == 0x205f or cp == 0x3000;
}
const ranges = [_]Range{
'''
text+=''.join(f'    .{{ .first = 0x{a:x}, .last = 0x{b:x}, .category = .{cat} }},\n' for a,b,cat in rows)+'};\n'
(Path(__file__).resolve().parents[1]/'src/tokenizer_unicode.zig').write_text(text)
